[theme]
base = "light"
backgroundColor = "#FEFAE0"
secondaryBackgroundColor = "#FEFAE0"
textColor = "#283618"
primaryColor = "#DDA15E"
font = "sans serif"
[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false